function model = generateModel(clutterRate, detectionProbability)
% GENERATEMODEL -- Generates a structure containing all simulation info.
%   model = generateModel(detectionProbabilty, clutterRate);
%
%   Declares all simulation information, except the ground truth.
%
%   See also generateTruth.
%
%   Inputs
%       clutterRate - integer. The number of expected clutter per
%           time-step. Clutter is assumed to generated by a Poisson point
%           process.
%       detectionProbability - double. The probability of the sensor
%           detecting a target-generated measurement.
%
%   Output
%       model - struct. A struct with the field declared in this function.
%% State and measurement space dimensions
model.xDimension = 4;
model.zDimension = 2;
%% Sampling period
model.T = 20e-3;
%% Linear motion model
% State transition matrix
model.A = [ eye(model.xDimension/2) model.T*eye(model.xDimension/2); ...
    zeros(model.xDimension/2) eye(model.xDimension/2)];
model.Atranspose = model.A'; %Precompute
model.u = zeros(model.xDimension, 1);
% Process noise
r0 = 0.3;
model.R = r0*[ (1/3)*(model.T^3)*eye(model.xDimension/2) 0.5*(model.T^2)*eye(model.xDimension/2);
    0.5*(model.T^2)*eye(model.xDimension/2) model.T*eye(model.xDimension/2)];
%% Linear observation model
% Observation matrix
model.C = [ eye(model.zDimension) zeros(model.zDimension) ];
model.Ctranspose = model.C';
% Measurement noise
q0 = 0.3;
model.Q = q0*eye(model.zDimension);
%% Detection probability
model.detectionProbability = detectionProbability;
%% Observation space
model.observationSpaceLimits = 500*[-1 1; -1 1];
model.observationSpaceVolume = prod(model.observationSpaceLimits(:, 2) - model.observationSpaceLimits(:, 1));
model.clutterRate = clutterRate;
%% OSPA parameters
model.ospaP = 2;
model.eOspaC = 5; % Euclidean cut-off
model.hOspaC = 1; % Hellinger cut-off
end